# Generated by Django 5.2.5 on 2026-02-03 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_movies'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Movies',
        ),
    ]
