# Generated by Django 5.2 on 2026-03-09 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0006_booking_is_paid_booking_razorpay_order_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='seat',
            name='is_reserved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='seat',
            name='reserved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
